spring.application.name=restful-api-inmap
spring.jpa.database=POSTGRESQL
spring.sql.init.platform=postgres
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
sendinblue.api.key=${SENDINBLUE_API_KEY}
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=none
server.port=${PORT:8080}
server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html,text/plain
server.compression.min-response-size=1024

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=465
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false

